### ISSUE TITLE
ObjectDeletedError and InvalidRequestError with tracebacks in nodepool-launcher.log

### ISSUE THREAD

**Issue by ConsoleCatzirl** [BonnyCI/projman#104]
```text
2017-02-02 22:44:33,870 ERROR nodepool.SubNodeLauncher: ObjectDeletedError launching subnode id: 1749 for node id: 294 in provider: cicloud error:
Traceback (most recent call last):
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodepool.py", line 747, in _run
    dt = self.launchSubNode(session)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodepool.py", line 858, in launchSubNode
    self.subnode.state = nodedb.READY
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodedb.py", line 170, in state
    session.commit()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 864, in commit
    self.transaction.commit()   
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 455, in commit
    self._prepare_impl()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 435, in _prepare_impl
    self.session.flush()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2080, in flush
    self._flush(objects)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2198, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2162, in _flush
    flush_context.execute()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, update)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 638, in _emit_update_statements
    lambda rec: (
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 518, in _collect_update_commands
    state, state_dict, attributes.PASSIVE_OFF)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 686, in get_history
    current = self.get(state, dict_, passive=passive)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 578, in get
    value = state._load_expired(state, passive)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 474, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 669, in load_scalar_attributes
    raise orm_exc.ObjectDeletedError(state)
ObjectDeletedError: Instance '<SubNode at 0x7f6e080c0810>' has been deleted, or its row is otherwise not present.
2017-02-02 22:44:33,874 ERROR nodepool.SubNodeLauncher: Exception deleting subnode id: 1749: for node id: 294:
Traceback (most recent call last):
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodepool.py", line 773, in _run
    self.nodepool.deleteSubNode(self.subnode, self.manager)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodepool.py", line 1355, in deleteSubNode
    if subnode.external_id:
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 578, in get
    value = state._load_expired(state, passive)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 474, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 664, in load_scalar_attributes
    only_load_props=attribute_names)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 219, in load_on_ident
    return q.one()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2718, in one
    ret = list(self)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2774, in _execute_and_instances
    close_with_result=True)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2765, in _connection_from_session
    **kw)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 956, in connection
    execution_options=execution_options)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 961, in _connection_for_bind
    engine, execution_options)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 376, in _connection_for_bind
    self._assert_active()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 277, in _assert_active
    % self._rollback_exception
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: Instance '<SubNode at 0x7f6e080c0810>' has been deleted, or its row is otherwise not present.
2017-02-02 22:44:33,875 ERROR nodepool.SubNodeLauncher: Exception in run method:
Traceback (most recent call last):
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodepool.py", line 728, in run
    self._run()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodepool.py", line 778, in _run
    return
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodedb.py", line 228, in __exit__
    self.session().commit()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 864, in commit
    self.transaction.commit()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 453, in commit
    self._assert_active(prepared_ok=True)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 277, in _assert_active
    % self._rollback_exception
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: Instance '<SubNode at 0x7f6e080c0810>' has been deleted, or its row is otherwise not present.
```

**Comment by ConsoleCatzirl** [comment]
These seem to have been happening for a while, the earliest occurrence I see was at ` 2017-01-20 20:08:51,980`
