### ISSUE TITLE
Traceback on handling status

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#105]
```
2017-02-03 23:06:41,176 DEBUG zuul.GithubWebhookListener: X-Github-Event: status
2017-02-03 23:06:41,299 ERROR zuul.GithubWebhookListener: Exception when handling event:
Traceback (most recent call last):
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/connection/github.py", line 90, in __dispatch_event
    event = method(request)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/connection/github.py", line 193, in _event_status
    pr_body = self.connection.getPullBySha(body['sha'])
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/connection/github.py", line 461, in getPullBySha
    pr_url = issue.pull_request.get('url')
AttributeError: 'IssueSearchResult' object has no attribute 'pull_request'
```

**Comment by missaugustina** [comment]
Is this issue resolved now?
