### ISSUE TITLE
Traceback on handling reviews

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#106]
```
==> /var/log/zuul/server.log <==
2017-02-03 23:26:38,592 ERROR zuul.Scheduler: Exception in run handler:
Traceback (most recent call last):
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1019, in run
    self.process_event_queue()
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1066, in process_event_queue
    change = pipeline.source.getChange(event, project)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/source/github.py", line 64, in getChange
    change.approvals = self.getPullReviews(project, change.number)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/source/github.py", line 99, in getPullReviews
    reviews = self.connection.getPullReviews(owner, project, number)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/connection/github.py", line 489, in getPullReviews
    self.github.pull_request(owner, project, number).reviews()]
AttributeError: 'PullRequest' object has no attribute 'reviews'
```

**Comment by omgjlk** [comment]
This might be because we're re-using a venv for zuul, and the requirements are not getting updated correctly. Going to try forcing an install of the newer github3.py code.

**Comment by omgjlk** [comment]
Was from old github3.py. Updated, closing issue.
