### ISSUE TITLE
Traceback on matching required approvals

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#108]
```
2017-02-04 00:37:07,791 ERROR zuul.Scheduler: Exception in run handler:
Traceback (most recent call last):
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1019, in run
    self.process_event_queue()
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1084, in process_event_queue
    pipeline.manager.addChange(change)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1444, in addChange
    if not f.matches(change):
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/model.py", line 1470, in matches
    if not self.matchesApprovals(change):
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/model.py", line 1204, in matchesApprovals
    return (self.matchesRequiredApprovals(change) and
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/model.py", line 1212, in matchesRequiredApprovals
    if self._match_approval_required_approval(rapproval, approval):
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/model.py", line 1190, in _match_approval_required_approval
    int(approval['value']) not in v):
KeyError: 'value'
```

**Comment by omgjlk** [comment]
Handle a review with state `DISMISSED` and throw it out.

**Comment by omgjlk** [comment]
An approval has a state of `APPROVED`.

**Comment by missaugustina** [comment]
Is this issue still outstanding? If so, could you update the ticket with more info so someone can pick it up? If you intend to do the work just assign it to yourself.

**Comment by missaugustina** [comment]
Per @j2sol on irc, this issue is resolved.
