### ISSUE TITLE
Traceback handling status event

### ISSUE THREAD

**Issue by gandelman-a** [BonnyCI/projman#109]
This is a new one that we're getting after all fixes last week merged and zuul has been restarted to pick them up:
 
```
2017-02-06 17:04:37,083 DEBUG zuul.GithubConnection: GitHub API rate limit remaining: 4789 reset: 1486403863
2017-02-06 17:04:37,083 ERROR zuul.GithubWebhookListener: Exception when handling event:
Traceback (most recent call last):
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/connection/github.py", line 90, in __dispatch_event
    event = method(request)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/connection/github.py", line 193, in _event_status
    pr_body = self.connection.getPullBySha(body['sha'])
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/connection/github.py", line 477, in getPullBySha
    if len(pulls) == 0:
IndexError: pop from empty list
2017-02-06 17:04:37,584 DEBUG gear.Worker.Zuul RPC Listener: Processing input on <gear.Connection 0x7fcb887c6e50 host: zuul.bonnyci-internal.portbleu.com port: 4730>
```

**Comment by gandelman-a** [comment]
This appeared to be stale .pyc bytecode running while up-to-code code had been checked out, causing the old bug to trigger but the traceback references the new code.  Cleaning out the stale pyc files from the virtualenv and restarting zuul seems to have fixed it.  We should reopen this if we hit this again, as there may be an issue with ansible checking out new code and re-installing it via pip.
