### ISSUE TITLE
Zuul hits traceback during reporting, when adding labels

### ISSUE THREAD

**Issue by gandelman-a** [BonnyCI/projman#113]
We currently have bonny configured to removed the 'approved' label as its starting its gate jobs, then add it back after its successfully completed them.  It currently hits an error when attempting to add the label. I'm not sure if this is a bug with the original github code, or if it was actually working at one point but broke after we upgraded our github3.py 
```

2017-02-07 21:09:08,926 ERROR zuul.DependentPipelineManager: Exception while reporting:
Traceback (most recent call last):
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1806, in _reportItem
    ret = self.sendReport(actions, self.pipeline.source, item)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1333, in sendReport
    ret = reporter.report(source, self.pipeline, item)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/reporter/github.py", line 62, in report
    self.setLabels(item)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/reporter/github.py", line 127, in setLabels
    self.connection.labelPull(owner, project, pr_number, label)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/connection/github.py", line 562, in labelPull
    pull_request.add_label(label)
  File "/opt/venvs/zuul/src/github3.py/github3/models.py", line 59, in __getattr__
    raise AttributeError(attribute)
AttributeError: add_label
2017-02-07 21:09:08,926 ERROR zuul.DependentPipelineManager: Exception while reporting:
Traceback (most recent call last):
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1806, in _reportItem
    ret = self.sendReport(actions, self.pipeline.source, item)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1333, in sendReport
    ret = reporter.report(source, self.pipeline, item)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/reporter/github.py", line 62, in report
    self.setLabels(item)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/reporter/github.py", line 127, in setLabels
    self.connection.labelPull(owner, project, pr_number, label)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/connection/github.py", line 562, in labelPull
    pull_request.add_label(label)
  File "/opt/venvs/zuul/src/github3.py/github3/models.py", line 59, in __getattr__
    raise AttributeError(attribute)
AttributeError: add_label
```

**Comment by gandelman-a** [comment]
https://github.com/BonnyCI/zuul/pull/22
