### ISSUE TITLE
zuul traceback when its unable to map issue to PR

### ISSUE THREAD

**Issue by gandelman-a** [BonnyCI/projman#118]
```
2017-02-10 18:55:49,371 ERROR zuul.GithubWebhookListener: Exception when handling event:
Traceback (most recent call last):
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/connection/github.py", line 90, in __dispatch_event
    event = method(request)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/connection/github.py", line 158, in _event_issue_comment
    pr_body = self._issue_to_pull_request(body)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/connection/github.py", line 206, in _issue_to_pull_request
    pr_body = self.connection.getPull(owner, project, number)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/connection/github.py", line 453, in getPull
    pr = self.github.pull_request(owner, project, number).as_dict()
AttributeError: 'NoneType' object has no attribute 'as_dict'
2017-02-10 19:00:02,061 DEBUG zuul.Gearman: Looking for lost builds
```

**Comment by omgjlk** [comment]
Would be good to have more info around this, like what PR this came in on or whatnot.
