### ISSUE TITLE
Opentech nodepool is can't connect to mysql

### ISSUE THREAD

**Issue by ConsoleCatzirl** [BonnyCI/projman#167]
Related: BonnyCI/projman#151

Our deploy to the new cloud is failing to bring up a working nodepool, it fails to connect to mysql on the opentech zuul host:

```text
2017-03-13 19:31:33,293 ERROR nodepool.NodePool: Exception in main loop:
Traceback (most recent call last):
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodepool.py", line 1274, in run
    self.updateConfig()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodepool.py", line 1246, in updateConfig
    self.reconfigureDatabase(config)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodepool.py", line 916, in reconfigureDatabase
    config.db = nodedb.NodeDatabase(config.dburi)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodedb.py", line 209, in __init__
    metadata.create_all(self.engine)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3762, in create_all
    tables=tables)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1855, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1848, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1060, in _do_get
    self._dec_overflow()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1057, in _do_get
    return self._create_connection()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/pymysql/connections.py", line 959, in connect
    raise exc
OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'zuul.internal.opentechsjc.bonnyci.org' ([Errno 111] Connection refused)")
```

**Comment by gandelman-a** [comment]
install-ci.yml hasnt finished installing zuul because its blocked on https://github.com/BonnyCI/hoist/pull/220

**Comment by ConsoleCatzirl** [comment]
Now that install-ci.yml runs to completion, this is no longer an issue.
