### ISSUE TITLE
Opentech nodepool can't upload images

### ISSUE THREAD

**Issue by ConsoleCatzirl** [BonnyCI/projman#168]
Our new nodepool deploy is failing to authenticate when trying to upload images:
```text
2017-03-13 20:55:19,989 INFO nodepool.builder.UploadWorker.0: Uploading DIB image build 0000000001 from /opt/nodepool/images/ubuntu-xenial-0000000001.qcow2 to cicloud
2017-03-13 20:55:20,052 ERROR nodepool.builder.UploadWorker.0: Failed to upload image ubuntu-xenial to provider cicloud
Traceback (most recent call last):
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/builder.py", line 882, in _uploadImage
    sha256=image.sha256,
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/provider_manager.py", line 327, in uploadImage
    **meta)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/openstackcloud.py", line 3368, in create_image
    current_image = self.get_image(name)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/openstackcloud.py", line 2673, in get_image
    return _utils._get_entity(self.search_images, name_or_id, filters)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/_utils.py", line 165, in _get_entity
    entities = func(name_or_id, filters, **kwargs)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/openstackcloud.py", line 1596, in search_images
    images = self.list_images()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/openstackcloud.py", line 1928, in list_images
    response = self._image_client.get(endpoint)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/openstackcloud.py", line 508, in _image_client
    config_version, image_client)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/openstackcloud.py", line 445, in _discover_image_endpoint
    versions = image_client.get('/')
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 223, in get
    return self.request(url, 'GET', **kwargs)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/_adapter.py", line 153, in request
    response = self.manager.submit_task(RequestTask(**kwargs))
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/task_manager.py", line 245, in submit_task
    return self.run_task(task=task, raw=raw)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/task_manager.py", line 256, in run_task
    return self._run_task(task, raw=raw)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/task_manager.py", line 270, in _run_task
    return task.wait(raw)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/task_manager.py", line 99, in wait
    self._traceback)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/task_manager.py", line 108, in run
    self.done(self.main(client))
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/_adapter.py", line 151, in main
    return request_method(**self.args)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 148, in request
    return self.session.request(url, method, **kwargs)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/positional/__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/keystoneauth1/session.py", line 491, in request
    auth_headers = self.get_auth_headers(auth)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/keystoneauth1/session.py", line 818, in get_auth_headers
    return auth.get_headers(self, **kwargs)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/keystoneauth1/plugin.py", line 90, in get_headers
    token = self.get_token(session)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 90, in get_token
    return self.get_access(session).auth_token
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 136, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/keystoneauth1/identity/generic/base.py", line 198, in get_auth_ref
    return self._plugin.get_auth_ref(session, **kwargs)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/keystoneauth1/identity/v3/base.py", line 167, in get_auth_ref
    authenticated=False, log=False, **rkwargs)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/keystoneauth1/session.py", line 766, in post
    return self.request(url, 'POST', **kwargs)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/positional/__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/keystoneauth1/session.py", line 655, in request
    raise exceptions.from_response(resp, method, url)
Unauthorized: The request you have made requires authentication. (HTTP 401) (Request-ID: req-5f19e1c3-8a77-48da-a32c-146ca0ce676b)
```

Related: BonnyCI/projman#151

**Comment by gandelman-a** [comment]
This was just a secrets issue, using the wrong password.

**Comment by ConsoleCatzirl** [comment]
The password in the secrets.yml file was corrected.
