### ISSUE TITLE
Errors merging code from hoist PR

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#61]
Tried to get zuul to test an open PR (with a `recheck` comment). Merger failed to create a zuul reference.

```
2016-12-17 00:34:56,040 DEBUG zuul.Repo: Merging refs/pull/10/head with args ['-
s', 'resolve', 'FETCH_HEAD']
2016-12-17 00:34:56,069 DEBUG zuul.Merger: Unable to merge {u'oldrev': None, u'n
ewrev': None, u'refspec': u'refs/pull/10/head', u'merge_mode': 2, u'connection_n
ame': u'github', u'number': 10, u'project': u'BonnyCI/hoist', u'url': u'https://
github.com/BonnyCI/hoist', u'branch': u'master', u'patchset': u'104fdae491489c59
4ec81911ea50b58eb274d5b1', u'ref': u'Z99095be32e334e50844fa98d49405718'}
Traceback (most recent call last):
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/merger/merger.py"
, line 266, in _mergeChange
    commit = repo.merge(item['refspec'], 'resolve')
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/merger/merger.py"
, line 154, in merge
    repo.git.merge(*args)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/git/cmd.py", line 424,
 in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/git/cmd.py", line 873,
 in _call_process
    return self.execute(call, **_kwargs)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/git/cmd.py", line 687,
 in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git merge -s resolve FETCH_HEAD
  stderr: '
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <zuul@zuul.(none)>) not allowed'
```

I think we're missing a zuul setting somewhere.

This was from testing PR https://github.com/BonnyCI/hoist/pull/10

**Comment by omgjlk** [comment]
After a restart of zuul-merger once deployed, I was able to get a passing check on a PR that was not directly on top of upstream master.

https://github.com/BonnyCI/hoist/pull/12
