### ISSUE TITLE
BonnyCI Service Outage - Nodepool ran out of disk space

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/projman#88]
### Timeline:
(times in PST)
10:47 jesusaur reported in irc a pull request hadn't merged. jlk noticed other jobs were also still open.
10:54 jlk reported the following from the logs: -bash: cannot create temp file for here-document: No space left on device and discovered 32 gigs in logs; Errors in nodepool-launcher: '403: quota exceeded' 
10:59 jlk purged logs freeing up space. jlk reported something was generating multi-hundred meg logs every day starting around the 10th. we're getting connection issues, kazoo.client (zookeeper).
11:03 jlk discovered Zookeeper went down, tracebacks in nodepool land, but our monitors don't seem to notice, says nodepool is A-OK, but we have no images or nodes
11:11 jlk restarted zookeeper: 
 - do we have a ops guide on restarting zookeeper for nodepool? 
 - infra docs point at https://zookeeper.apache.org/doc/trunk/zookeeperAdmin.html
 - I believe we had talked about when a single node ZK is restarted you may want to wipe out all the data
11:19 Nodepool was not restarted: per jlk, I didn't restart nodepool, all I did was clear disk space and restart zookeeper.
11:28 adam_g confirmed tests were running again

### How was the outage discovered?

Several folks on the team noticed PR's weren't merging and that jobs had been open for awhile.

### What steps were taken to restore service?

Nodepool logs were deleted to free up space.
Zookeeper was restarted.

### What steps were taken to find root cause?

Logs were evaluated and server status history was reviewed via the Datadog monitors.

###When was service restored?

11:28 am PST

###Root Cause Analysis:

Nodepool ran out of disk space possibly due to excessive logging.
Further research is needed to determine if zookeeper down caused bloat which caused numerous other actions, or if the bloat itself caused communication issues.

###Next Steps: (check box when tickets are made)

- [x] add monitoring for disk usage on nodepool server
- [x] discover why nodepool monitoring reported that everything was fine when it wasn't, and fix it.
- [x] add monitoring for zookeeper connectivity issues
- [x] how often do we currently delete logs? how are we going to do this for BonnyCI users?
- [x] add alert for zuul processes waiting for a long period of time

**Comment by missaugustina** [comment]
Leaving this open for root cause analysis. What caused the Zookeeper connectivity issues? Did Zookeeper filling up the logs so that Nodepool's disk was full cause the outage or was it something else?

**Comment by missaugustina** [comment]
To view logs, ssh to contrasjc-bastion then just type "nodepool" to ssh to nodepool, "zuul" to ssh to zuul.

**Comment by missaugustina** [comment]
From nodepool deleter logs:
`
2017-01-20 10:02:50,110 ERROR nodepool.NodePool: Exception cleaning up leaked nodes
Traceback (most recent call last):
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodepool.py", line 1513, in periodicCleanup
    self.cleanupLeakedInstances()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodepool.py", line 1524, in cleanupLeakedInstances
    servers = manager.listServers()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/provider_manager.py", line 339, in listServers
    return self._client.list_servers()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/openstackcloud.py", line 1740, in list_servers
    self._servers = self._list_servers(detailed=detailed)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/openstackcloud.py", line 1762, in _list_servers
    for server in servers
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/shade/_utils.py", line 422, in shade_exceptions
    raise exc.OpenStackCloudException(error_message)

OpenStackCloudException: Error fetching server list on contra-sjc:: (Inner Exception: Unable to establish connection to https://contra-sjc.openstack.blueboxgrid.com:8774/v2/f7b8f88b8c594d8ea3cdddec801bc6ec/servers/detail: HTTPSConnectionPool(host='contra-sjc.openstack.blueboxgrid.com', port=8774): Max retries exceeded with url: /v2/f7b8f88b8c594d8ea3cdddec801bc6ec/servers/detail (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff9b40e5690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)))
2017-01-20 12:15:40,053 ERROR nodepool.NodePool: Exception in periodic check:
Traceback (most recent call last):
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodepool.py", line 1585, in _doPeriodicCheck
    self.periodicCheck(session)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodepool.py", line 1594, in periodicCheck
    for node in session.getNodes():
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/nodepool/nodedb.py", line 254, in getNodes
    return exp.all()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2613, in all
    return list(self)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2774, in _execute_and_instances
    close_with_result=True)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2765, in _connection_from_session
    **kw)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 956, in connection
    execution_options=execution_options)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 961, in _connection_for_bind
    engine, execution_options)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 397, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/venvs/nodepool/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", l

`

**Comment by missaugustina** [comment]
Most of the logs were deleted from the nodepool server but the syslogs are still intact. Here's what I've found (times in UTC, outage was identified at 06:00 UTC):

```
Jan 20 00:01:32 nodepool dd.dogstatsd[16617]: ERROR (dogstatsd.py:326): Unable to post payload.#012Traceback (most recent call last):#012  File "/opt/datadog-agent/agent/dogstatsd.py", line 316, in submit_http#012    r = requests.post(url, data=data, timeout=5, headers=headers)#012  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 108, in post#012    return request('post', url, data=data, json=json, **kwargs)#012  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/api.py", line 50, in request#012    response = session.request(method=method, url=url, **kwargs)#012  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 465, in request#012    resp = self.send(prep, **send_kwargs)#012  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/sessions.py", line 573, in send#012    r = adapter.send(request, **kwargs)#012  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/adapters.py", line 433, in send#012    raise ReadTimeout(e, request=request)#012ReadTimeout: HTTPConnectionPool(host='localhost', port=17123): Read timed out. (read timeout=5)


Jan 20 00:02:41 nodepool sh[29829]: OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'zuul.bonnyci-internal.portbleu.com' ([Errno -3] Temporary failure in name resolution)")

Jan 20 01:18:03 nodepool sh[29802]: IOError: [Errno 28] No space left on device
```

**Comment by missaugustina** [comment]
Datadog logs also still intact, confirm some kind of network connectivity issue and then the disk full error:

Datadog logs:

```
Frequent timeout errors starting 1/13
2017-01-17 01:01:39 UTC | ERROR | dd.dogstatsd | dogstatsd(dogstatsd.py:432) | Error receiving datagram `nodepool.job.zuul:launcher-shutdown.runtime:627.000000|ms`
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/dogstatsd.py", line 420, in start
    aggregator_submit(message)
  File "/opt/datadog-agent/agent/aggregator.py", line 612, in submit_packets
    parsed_packets = self.parse_metric_packet(packet)
  File "/opt/datadog-agent/agent/aggregator.py", line 467, in parse_metric_packet
    raise Exception(u'Unparseable metric packet: %s' % packet)
Exception: Unparseable metric packet: nodepool.job.zuul:launcher-shutdown.runtime:627.000000|ms
2017-01-17 01:01:39 UTC | ERROR | dd.dogstatsd | dogstatsd(dogstatsd.py:432) | Error receiving datagram `nodepool.job.zuul:launcher-shutdown.builds:1|c`
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/dogstatsd.py", line 420, in start
    aggregator_submit(message)
  File "/opt/datadog-agent/agent/aggregator.py", line 612, in submit_packets
    parsed_packets = self.parse_metric_packet(packet)
  File "/opt/datadog-agent/agent/aggregator.py", line 467, in parse_metric_packet
    raise Exception(u'Unparseable metric packet: %s' % packet)
Exception: Unparseable metric packet: nodepool.job.zuul:launcher-shutdown.builds:1|c

2017-01-17 02:01:14 UTC | ERROR | dd.dogstatsd | dogstatsd(dogstatsd.py:326) | Unable to post payload.

Logs for 2017-01-20:
First timeout:
2017-01-20 00:01:32 UTC | ERROR | dd.dogstatsd | dogstatsd(dogstatsd.py:326) | Unable to post payload.

2017-01-20 06:39:02 UTC | ERROR | dd.dogstatsd | checks.check_status(check_status.py:166) | Error persisting status
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/check_status.py", line 164, in persist
    f.close()
IOError: [Errno 28] No space left on device

Collector logs:
2017-01-20 01:18:05 UTC | ERROR | dd.collector | checks.collector(unix.py:747) | Cannot compute CPU stats
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/system/unix.py", line 605, in check
    output, _, _ = get_subprocess_output(['mpstat', '1', '3'], self.logger)
  File "/opt/datadog-agent/agent/utils/subprocess_output.py", line 38, in get_subprocess_output
    raise SubprocessOutputEmptyError("get_subprocess_output expected output but had none.")
SubprocessOutputEmptyError: get_subprocess_output expected output but had none.
2017-01-20 01:18:06 UTC | ERROR | dd.collector | checks.collector(unix.py:220) | Cannot extract IO statistics
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/system/unix.py", line 122, in check
    stdout, _, _ = get_subprocess_output(['iostat', '-d', '1', '2', '-x', '-k'], self.logger)
  File "/opt/datadog-agent/agent/utils/subprocess_output.py", line 38, in get_subprocess_output
    raise SubprocessOutputEmptyError("get_subprocess_output expected output but had none.")
SubprocessOutputEmptyError: get_subprocess_output expected output but had none.
2017-01-20 01:18:06 UTC | ERROR | dd.collector | checks.collector(collector.py:350) | Unable to get processes metrics
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/collector.py", line 348, in run
    processes = sys_checks['processes'].check(self.agentConfig)
  File "/opt/datadog-agent/agent/checks/system/unix.py", line 561, in check
    output, _, _ = get_subprocess_output(['ps', ps_arg], self.logger)
  File "/opt/datadog-agent/agent/utils/subprocess_output.py", line 38, in get_subprocess_output
    raise SubprocessOutputEmptyError("get_subprocess_output expected output but had none.")
SubprocessOutputEmptyError: get_subprocess_output expected output but had none.

Next log not until:
2017-01-20 06:30:28 UTC | INFO | dd.collector | checks.collector(collector.py:530) | Finished run #131760. Collection time: 4.16s. Emit time: 0.05s

Jump in logging here:
2017-01-20 02:08:41 UTC | INFO | dd.dogstatsd | dogstatsd(dogstatsd.py:262) | Flush #251022017-01-20 06:27:59 UTC | INFO | dd.dogstatsd | dogstatsd(dogstatsd.py:262) | Flush #252560: flushed 1 metric, 0 events, and 0 service check runs
2017-01-20 06:28:09 UTC | INFO | dd.dogstatsd | dogstatsd(dogstatsd.py:262) | Flush #252561: flushed 1 metric, 0 events, and 0 service check runs
```

**Comment by missaugustina** [comment]
After looking in the Zuul logs it doesn't look like Zuul experienced any service interruption or degradation. Because we don't have Zookeeper logs or Nodepool logs from the outage, we are unable to determine root cause at this point in time. Given the logs showed a network interruption and there was initial evidence suggesting that Zookeeper may have had a network connectivity issue, it's possible the cause was a network connectivity issue that Zookeeper was unable to recover from. This resulted in excessive logging from Zookeeper which filled up the root partition ultimately causing the Nodepool server failure.

Going forward, there are issues now filed to add monitoring and alerting to the possible suspects that may have caused the outage. We will pay particularly close attention to Zookeeper to see if we notice a continuing trend of instability.
