### ISSUE TITLE
hoist-checks fails with No Such File

### ISSUE THREAD

**Issue by omgjlk** [BonnyCI/projman#96]
See https://github.com/BonnyCI/hoist/pull/73#issuecomment-275204888

The job is failing fast with just that error. Seems it was introduced not long ago. Assigning this to @jesusaurus

**Comment by ConsoleCatzirl** [comment]
The "No Such File" refers to the path in the link not existing on the log host. This is likely a symptom of a failure mode causing the test output to not get pushed to the log host. I will investigate further.

**Comment by ConsoleCatzirl** [comment]
The only log entries for today in zuul's server.log are four occurrences of this traceback:
```
2017-01-25 04:49:27,928 ERROR zuul.DependentPipelineManager: Exception while reporting:
Traceback (most recent call last):
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1806, in _reportItem
    ret = self.sendReport(actions, self.pipeline.source, item)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/scheduler.py", line 1333, in sendReport
    ret = reporter.report(source, self.pipeline, item)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/reporter/github.py", line 62, in report
    self.setLabels(item)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/reporter/github.py", line 127, in setLabels
    self.connection.labelPull(owner, project, pr_number, label)
  File "/opt/venvs/zuul/local/lib/python2.7/site-packages/zuul/connection/github.py", line 345, in labelPull
    def _get_installation_key(self, user_id=None):
AttributeError: 'Issue' object has no attribute 'add_label'
```

**Comment by ConsoleCatzirl** [comment]
That traceback is not related to test output failing to be copied to the logs host.

**Comment by ConsoleCatzirl** [comment]
Zuul's launcher-debug.log shows that the log was skipped:
```
2017-01-25 19:14:02,017 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible output:
2017-01-25 19:14:02,017 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible output: PLAY RECAP *********************************************************************
2017-01-25 19:14:02,017 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible output: node                       : ok=4    changed=4    unreachable=0    failed=1
2017-01-25 19:14:02,018 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible output:
2017-01-25 19:14:02,043 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible exit code: 2
2017-01-25 19:14:02,043 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible post command: ['ansible-playbook', '/tmp/tmpz4TIEk/ansible/post_playbook', '-e', 'success=False', '-e@/tmp/tmpz4TIEk/ansible/vars.yaml', '-v']
2017-01-25 19:14:02,336 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible post output: Using /tmp/tmpz4TIEk/ansible/ansible_pre_post.cfg as config file
2017-01-25 19:14:02,460 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible post output:
2017-01-25 19:14:02,460 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible post output: PLAY [Publishers] **************************************************************
2017-01-25 19:14:02,477 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible post output:
2017-01-25 19:14:02,477 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible post output: TASK [zuul_log] ****************************************************************
2017-01-25 19:14:02,676 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible post output: changed: [node] => {"changed": true}
2017-01-25 19:14:02,677 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible post output:
2017-01-25 19:14:02,677 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible post output: TASK [zuul_log] ****************************************************************
2017-01-25 19:14:02,701 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible post output: skipping: [node] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
2017-01-25 19:14:02,702 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible post output:
2017-01-25 19:14:02,702 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible post output: PLAY RECAP *********************************************************************
2017-01-25 19:14:02,703 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible post output: node                       : ok=1    changed=1    unreachable=0    failed=0
2017-01-25 19:14:02,703 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible post output:
2017-01-25 19:14:02,730 DEBUG zuul.NodeWorker.ubuntu-xenial-cicloud-70: Ansible post exit code: 0
```
